export const faqs: { id: number; q: string; a: string }[] = [
  {
    id: 0,
    q: "How does URL shortening work?",
    a: "URL shortening is a technique used to create a shorter version of a long URL, making it easier to share. Our tool generates a unique shortened URL that redirects to the original long URL when clicked.",
  },
  {
    id: 1,
    q: "Can I customize the shortened URLs?",
    a: "Yes, you can! Our platform allows you to customize the shortened URLs to make them more memorable or branded. Simply use our custom URL feature to create personalized links.",
  },
  {
    id: 2,
    q: "How can I track the performance of my shortened URLs?",
    a: "We offer analytics tools that allow you to track various metrics, such as the number of clicks, geographic location of users, and referral sources. This data helps you understand how your links are performing and make informed decisions.",
  },
  {
    id: 3,
    q: " Can I download the QR codes generated by your tool?",
    a: "Absolutely! Once you generate a QR code for your URL, you can download it in various formats, such as PNG or SVG, for use in print or digital media",
  },
  {
    id: 4,
    q: "Is there a way to edit or delete shortened URLs?",
    a: "Yes, if you have an account with us, you can manage your shortened URLs, edit their destination, or delete them as needed. If you're using our service without an account, please contact us for assistance with editing or deleting links.",
  },
];
